version: "3.8"

services:
  ailogix:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    env_file: .env
    depends_on:
      - ollama
      - chromadb
    networks:
      - log-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - log-network

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/data
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    networks:
      - log-network

volumes:
  ollama_data:
  chroma_data:

networks:
  log-network:
    driver: bridge